{
  name: 'Solar-Skiff',
  cost: 1,
  attack: 0,
  trade: 2,
  heal: 0,
  defense: 0,
  skill: 'draw',
  faction: 'blue',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 0,
    skill: ''
  },
  imgsrc: './img/Blue/Cards/Solar-Skiff.png'
}, {
  name: 'Colony-Seed-Ship',
  cost: 5,
  attack: 3,
  trade: 3,
  heal: 3,
  skill: '',
  faction: 'blue',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 0,
    skill: ''
  },
  imgsrc: './img/Blue/Cards/Colony-Seed-Ship.png'
}, {
  name: 'peaceKeeper',
  cost: 6,
  attack: 6,
  trade: 0,
  heal: 6,
  defense: 0,
  skill: 'draw',
  faction: 'blue',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 3,
    skill: ''
  },
  imgsrc: './img/Blue/Cards/PeaceKeeper.png'
}, {
  name: 'Trade-Hauler',
  cost: 2,
  attack: 0,
  trade: 3,
  heal: 3,
  defense: 0,
  skill: '',
  faction: 'blue',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 0,
    skill: ''
  },
  imgsrc: './img/Blue/Cards/Trade-Hauler.png'
}, {
  name: 'Patrol-Cutter',
  cost: 3,
  attack: 3,
  trade: 2,
  heal: 4,
  defense: 0,
  skill: '',
  faction: 'blue',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 0,
    skill: ''
  },
  imgsrc: './img/Blue/Cards/Patrol-Cutter.png'
}, {
  name: 'cargoPod',
  cost: 3,
  attack: 3,
  trade: 3,
  heal: 0,
  defense: 0,
  skill: '',
  faction: 'green',
  scrap: true,
  scrapValue: {
    trade: 0,
    attack: 3,
    skill: ''
  },
  imgsrc: './img/Green/Cards/Cargo-Pod.png'
}, {
  name: 'Moonwurm',
  cost: 7,
  attack: 8,
  trade: 0,
  heal: 0,
  defense: 0,
  skill: 'draw',
  faction: 'green',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 3,
    skill: ''
  },
  imgsrc: './img/Green/Cards/Moonwurm.png'
}, {
  name: 'Predator',
  cost: 2,
  attack: 4,
  trade: 0,
  heal: 0,
  defense: 0,
  skill: 'draw',
  faction: 'green',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 3,
    skill: ''
  },
  imgsrc: './img/Green/Cards/Predator.png'
}, {
  name: 'Battle-Bot',
  cost: 1,
  attack: 4,
  trade: 0,
  heal: 0,
  skill: '',
  defense: 0,
  faction: 'red',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 3,
    skill: ''
  },
  imgsrc: './img/Red/Cards/Battle-Bot.png'
}, {
  name: 'Convoy-Bot',
  cost: 3,
  attack: 6,
  trade: 0,
  heal: 0,
  skill: '',
  defense: 0,
  faction: 'red',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 3,
    skill: ''
  },
  imgsrc: './img/Red/Cards/Convoy-Bot.png'
}, {
  name: 'Mech-Cruiser',
  cost: 5,
  attack: 6,
  trade: 0,
  heal: 0,
  skill: '',
  defense: 0,
  faction: 'red',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 3,
    skill: ''
  },
  imgsrc: './img/Red/Cards/Mech-Cruiser.png'
}, {
  name: 'Mining-Mech',
  cost: 4,
  attack: 3,
  trade: 3,
  heal: 0,
  skill: '',
  defense: 0,
  faction: 'red',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 3,
    skill: ''
  },
  imgsrc: './img/Red/Cards/Mining-Mech.png'
}, {
  name: 'Repair-Bot',
  cost: 2,
  attack: 0,
  trade: 2,
  heal: 0,
  skill: '',
  defense: 0,
  faction: 'red',
  scrap: true,
  scrapValue: {
    trade: 0,
    attack: 2,
    skill: ''
  },
  imgsrc: './img/Red/Cards/Repair-Bot.png'
}, {
  name: 'The-Wrecker',
  cost: 7,
  attack: 6,
  trade: 0,
  heal: 0,
  skill: 'draw',
  defense: 0,
  faction: 'red',
  scrap: false,
  scrapValue: {
    trade: 0,
    attack: 2,
    skill: ''
  },
  imgsrc: './img/Red/Cards/The-Wrecker.png'
}, {
  name: 'Heavy-Cruiser',
  cost: 5,
  attack: 4,
  trade: 0,
  heal: 0,
  skill: 'draw',
  defense: 0,
  faction: 'red',
  scrap: false,
  scrapValue: {
    trade: 4,
    attack: 0,
    skill: 'draw'
  },
  imgsrc: './img/Yellow/Cards/Heavy-Cruiser.png'
}, {
  name: 'Gunship',
  cost: 4,
  attack: 5,
  trade: 0,
  heal: 0,
  skill: '',
  defense: 0,
  faction: 'red',
  scrap: true,
  scrapValue: {
    trade: 4,
    attack: 0,
    skill: ''
  },
  imgsrc: './img/Yellow/Cards/Gunship.png'
}